# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-10 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Computer_name', models.CharField(max_length=255)),
                ('Computer_code', models.IntegerField()),
                ('Computer_model', models.CharField(max_length=255)),
                ('Computer_price', models.CharField(max_length=255)),
                ('Computer_status', models.IntegerField()),
                ('Computer_departmen', models.CharField(max_length=255)),
                ('Computer_people', models.CharField(max_length=255)),
                ('Computer_source', models.CharField(max_length=255)),
                ('Computer_comment', models.CharField(max_length=255)),
                ('createtime', models.DateTimeField(auto_now=True)),
                ('uptime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComputerChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ComputerChange_name', models.CharField(max_length=255)),
                ('ComputerChange_code', models.IntegerField()),
                ('ComputerChange_model', models.CharField(max_length=255)),
                ('ComputerChange_price', models.CharField(max_length=255)),
                ('ComputerChange_status', models.IntegerField()),
                ('ComputerChange_departmen', models.CharField(max_length=255)),
                ('ComputerChange_now', models.CharField(max_length=255)),
                ('ComputerChange_source', models.CharField(max_length=255)),
                ('ComputerChange_comment', models.CharField(max_length=255)),
                ('createtime', models.DateTimeField(auto_now=True)),
                ('uptime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_apply_name', models.CharField(max_length=255)),
                ('job_handle_name', models.CharField(max_length=255)),
                ('job_apply_type', models.IntegerField()),
                ('job_apply_desc', models.CharField(max_length=255)),
                ('job_status', models.IntegerField()),
                ('createtime', models.DateTimeField(auto_now=True)),
                ('uptime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localhost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Localhost_id', models.IntegerField()),
                ('Localhost_memory', models.IntegerField()),
                ('Localhost_cpuifnfo', models.IntegerField()),
                ('Localhost_network', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_name', models.CharField(max_length=255)),
                ('record_number', models.IntegerField()),
                ('record_departmen', models.CharField(max_length=255)),
                ('record_port', models.CharField(max_length=255)),
                ('record_status', models.IntegerField()),
                ('createtime', models.DateTimeField(auto_now=True)),
                ('uptime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_password', models.CharField(max_length=255)),
                ('user_role', models.IntegerField()),
                ('user_user', models.CharField(max_length=255)),
                ('user_phone', models.BigIntegerField()),
                ('user_mail', models.CharField(max_length=255)),
                ('user_status', models.IntegerField()),
                ('createtime', models.DateTimeField(auto_now=True)),
                ('uptime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
